//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiplomaThesisSystemMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DiplomaThesisTopic
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DiplomaThesisTopic()
        {
            this.Student = new HashSet<Student>();
            this.Vote = new HashSet<Vote>();
        }
    
        public int ID { get; set; }
        public string ReviewerID { get; set; }
        public string TeacherID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string NumberOfStudents { get; set; }
        public string FieldOfStudy { get; set; }
        public string Degree { get; set; }
        public string Availability { get; set; }
        public string Status { get; set; }
    
        public virtual Reviewer Reviewer { get; set; }
        public virtual Teacher Teacher { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Student> Student { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Vote> Vote { get; set; }
    }
}
