//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiplomaThesisSystemMVC.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DiplomaThesisSystemEntities : DbContext
    {
        public DiplomaThesisSystemEntities()
            : base("name=DiplomaThesisSystemEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CommisionTeacher> CommisionTeacher { get; set; }
        public virtual DbSet<Defence> Defence { get; set; }
        public virtual DbSet<DiplomaThesis> DiplomaThesis { get; set; }
        public virtual DbSet<DiplomaThesisTopic> DiplomaThesisTopic { get; set; }
        public virtual DbSet<Review> Review { get; set; }
        public virtual DbSet<Reviewer> Reviewer { get; set; }
        public virtual DbSet<Student> Student { get; set; }
        public virtual DbSet<Teacher> Teacher { get; set; }
        public virtual DbSet<ThesisDefenceCommision> ThesisDefenceCommision { get; set; }
        public virtual DbSet<Vote> Vote { get; set; }
    }
}
