//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiplomaThesisSystemMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Student()
        {
            this.Defence = new HashSet<Defence>();
        }
    
        public string ID { get; set; }
        public Nullable<int> ReviewID { get; set; }
        public Nullable<int> DiplomaThesisTopicID { get; set; }
        public string SupervisorID { get; set; }
        public Nullable<int> DiplomaThesisID { get; set; }
        public int StudentID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Degree { get; set; }
        public Nullable<int> Semester { get; set; }
        public string FieldOfStudy { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Defence> Defence { get; set; }
        public virtual DiplomaThesis DiplomaThesis { get; set; }
        public virtual DiplomaThesisTopic DiplomaThesisTopic { get; set; }
        public virtual Review Review { get; set; }
        public virtual Teacher Teacher { get; set; }
    }
}
