//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiplomaThesisSystemMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThesisDefenceCommision
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ThesisDefenceCommision()
        {
            this.CommisionTeacher = new HashSet<CommisionTeacher>();
            this.Defence = new HashSet<Defence>();
        }
    
        public int ID { get; set; }
        public string SupervisorID { get; set; }
        public string ReviewerID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CommisionTeacher> CommisionTeacher { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Defence> Defence { get; set; }
        public virtual Reviewer Reviewer { get; set; }
        public virtual Teacher Teacher { get; set; }
    }
}
